var sweep_width_wing=[{
                        altitude:150,
                        visibility:[{
                            value:1.9,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:1.3
                                }]
                            },
                           {
                            value:5.6,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0.2
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:1.3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:1.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:2.8
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:1.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:1.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:3.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:5
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:3.7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:4.8
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:5.4
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:5.4
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:5.6
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:5.6
                                }]
                            },
                            {
                            value:9.3,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0.2
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:1.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:2.8
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:3.5
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:3.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:4.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:4.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:6.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:8.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:5.0//9.3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:4.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:5.7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:8.0
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:8.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:9.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:9.4
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:10
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:10
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:10.7
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:10.7
                                }]
                            }
                    
                            ]
                        
                        
                   
                        
                        
},
{
                        altitude:300,
                        visibility:[{
                            value:1.9,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:1.5
                                }]
                            },
                           {
                            value:5.6,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0.2
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:1.3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:1.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:2.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:2.8
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:1.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:1.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:4.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:5
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:3.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:4.8
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:5.4
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:5.4
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:5.6
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:5.6
                                }]
                            },
                            {
                            value:9.3,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0.2
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:1.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:3.3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:3.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:4.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:4.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:4.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:6.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:8.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:5.1//9.4
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:4.3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:5.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:8
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:8.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:9.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:9.4
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:10
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:10
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:10.6
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:10.7
                                }]
                            }
                    
                            ]
                        
                        
                   
                        
                        
},
{
                        altitude:600,
                        visibility:[{
                            value:1.9,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:0.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:0.4
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:0.4
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:0.4
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:0.4
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:0.4
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:0.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:0.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:0.9
                                }]
                            },
                           {
                            value:5.6,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:1.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:2.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:2.8
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:1.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:1.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:4.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:4.8
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:3.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:4.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:5.4
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:5.4
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:5.6
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:5.6
                                }]
                            },
                            {
                            value:9.3,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:1.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:3.3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:3.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:4.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:4.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:4.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:6.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:8.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:9.3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:4.3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:6.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:8
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:8.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:9.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:9.4
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:10
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:10
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:10.6
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:10.7
                                }]
                            }
                    
                            ]
                        
                      
}
]

