var saris_registered_services=[{
        service_name:"RAE",
        service_type:"WMS",
        service_url:"http://www.rae.gr/geoserver/wms",
        service_server_type:"Geoserver",
        service_predifened_layers:[
                                    "rae_status:V_ZONES_APOKLEISMOU_GEO",
                                    "rae_status:V_SDI_R_ANEMOGENNHTRIES11"
                                  ]
    },
    {
        service_name:"GeoDataGov",
        service_type:"WMS",
        service_url:"http://geodata.gov.gr/geoserver/wms",
        service_server_type:"Geoserver",
        service_predifened_layers:[
                                    "geodata.gov.gr:0adb0521-2223-43cd-96d3-d816ad7a193c"
                                  ]
    },
    {
        service_name:"ESRI",
        service_type:"WMS",
        service_url:"http://sampleserver1.arcgisonline.com/ArcGIS/services/Specialty/ESRI_StatesCitiesRivers_USA/MapServer/WMSServer",
        service_server_type:"Geoserver",
        service_predifened_layers:[
                                    "0"
                                  ]
    }]

