var sweep_width_helicopter=[{
                        altitude:150,
                        visibility:[{
                            value:1.9,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:1.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:1.3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:1.5
                                }]
                            },
                           {
                            value:5.6,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0.2
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:1.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:2.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:2.8
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:3.0
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:3.3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:3.5
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:3.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:4.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:5.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:6.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:3.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:4.4
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:5.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:5.7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:5.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:6.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:6.3
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:6.3
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:6.3
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:6.5
                                }]
                            },
                            {
                            value:9.3,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0.2
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:3.5
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:3.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:4.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:4.3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:4.8
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:5
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:2.8
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:2.8
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:5.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:7.2
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:9.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:10.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:3.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:6.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:9.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:9.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:10.2
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:10.6
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:11.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:11.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:11.7
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:11.9
                                }]
                            }
                    
                            ]
                        
                        
                   
                        
                        
},
{
                        altitude:300,
                        visibility:[{
                            value:1.9,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:1.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:1.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:1.3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:1.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:1.3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:1.3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:1.3
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:1.5
                                }]
                            },
                           {
                            value:5.6,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0.2
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:1.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:2.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:2.8
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:3.0
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:3.3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:3.5
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:3.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:4.8
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:5.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:6.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:3.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:4.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:5.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:5.7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:5.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:6.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:6.3
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:6.3
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:6.3
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:6.5
                                }]
                            },
                            {
                            value:9.3,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0.2
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:3.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:3.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:4.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:5.0
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:5
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:3
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:5.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:7.2
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:9.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:10.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:6.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:9.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:9.8
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:10.4
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:10.6
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:11.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:11.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:11.7
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:11.9
                                }]
                            }
                    
                            ]
                        
                        
                   
                        
                        
},
{
                        altitude:600,
                        visibility:[{
                            value:1.9,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:0.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:0.7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:0.9
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:1.1
                                }]
                            },
                           {
                            value:5.6,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:1.5
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:2.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:2.8
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:3.0
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:3.3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:3.5
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:2.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:3.9
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:4.8
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:5.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:5.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:3.5
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:4.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:5.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:5.7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:5.9
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:5.9
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:6.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:6.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:6.3
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:6.3
                                }]
                            },
                            {
                            value:9.3,
                            data:[{
                                vsl_subtype:"PIW",
                                length:null,
                                persons:null,
                                sweep:0
                                },{
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:1,
                                sweep:2.2
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:4,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:6,
                                sweep:3.7
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:8,
                                sweep:3.9
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:10,
                                sweep:4.3
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:15,
                                sweep:4.6
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:20,
                                sweep:5
                                },
                                {
                                vsl_subtype:"RAFT",
                                length:null,
                                persons:25,
                                sweep:5.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:2,
                                persons:null,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:5,
                                persons:null,
                                sweep:3.1
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:6,
                                persons:null,
                                sweep:5.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:10,
                                persons:null,
                                sweep:7.4
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:16,
                                persons:null,
                                sweep:9.6
                                },
                                {
                                vsl_subtype:"POWER_BOAT",
                                length:24,
                                persons:null,
                                sweep:10.6
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:5,
                                persons:null,
                                sweep:5.2
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:8,
                                persons:null,
                                sweep:7
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:12,
                                persons:null,
                                sweep:9.1
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:15,
                                persons:null,
                                sweep:9.8
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:21,
                                persons:null,
                                sweep:10.4
                                },
                                {
                                vsl_subtype:"SAILING",
                                length:25,
                                persons:null,
                                sweep:10.6
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:27,
                                persons:null,
                                sweep:11.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:46,
                                persons:null,
                                sweep:11.1
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:91,
                                persons:null,
                                sweep:11.7
                                },
                                {
                                vsl_subtype:"SHIP",
                                length:350,
                                persons:null,
                                sweep:11.9
                                }]
                            }
                    
                            ]
                        
                      
}
]

